### ISSUE TITLE
NameError: name 'SourceQuery' is not defined for a server

### ISSUE THREAD

**Issue by FleuryK** [DiscordGSM/DiscordGSM#10]
Hello. I've a problem with your bot :
```Future exception was never retrieved
future: <Future finished exception=NameError("name 'SourceQuery' is not defined")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/container/servers.py", line 82, in query_save_cache
    query = SourceQuery(str(server['addr']), int(server['port']))
NameError: name 'SourceQuery' is not defined
Future exception was never retrieved
future: <Future finished exception=NameError("name 'SourceQuery' is not defined")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/container/servers.py", line 82, in query_save_cache
    query = SourceQuery(str(server['addr']), int(server['port']))
NameError: name 'SourceQuery' is not defined
```

How to fix this problem? And excellent job for your bot.

OS : Debian 10 on VPS.
Version of Python installed : 3.7.3.
DiscordGSM 1.8.1

**Comment by olli-e** [comment]
sounds like you have not imported sourcequery, check that!

**Comment by FleuryK** [comment]
OK, i've found my problem.

I don't why this file is automatically deleted.

Thank you for your help.
